// Auto-generated file. DO NOT EDIT.
export const SharedConstants = {
  CONSTANT_UNSPECIFIED: 0,
  MAX_BLE_NAME_LENGTH: 29,
  START_TEMPERATURE: 30,
  HISTORY_ID_SENSOR_BAKE_MODE: 4000,
  HISTORY_ID_ADRC_TEST_MODE: 4001,
  HISTORY_ID_STEP_RESPONSE: 4002,
  MAX_PROFILE_NAME_LENGTH: 50,
  MAX_REFLOW_SEGMENTS: 10,
  MAX_REFLOW_PROFILES: 10,
  MAX_HISTORY_CHUNK: 100,
} as const
